/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package example.gradle.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin

/**
 * A simple 'hello world' plugin.
 */
class GrooyPluginTemplatePlugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Edit from plugin 'example.gradle.plugin.greeting'")
            }
        }
    }
}
