/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package example.gradle.plugin

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'example.gradle.plugin.greeting' plugin.
 */
class GrooyPluginTemplatePluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("example.gradle.plugin.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
